// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.EntityFrameworkCore.EntityFrameworkCore;

#nullable disable

namespace ProductManagement.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ProductManagementDbContext))]
    partial class ProductManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductManagement.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 431, DateTimeKind.Utc).AddTicks(952),
                            IsDeleted = false,
                            Name = "Category-1"
                        },
                        new
                        {
                            Id = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 431, DateTimeKind.Utc).AddTicks(985),
                            IsDeleted = false,
                            Name = "Category-2"
                        },
                        new
                        {
                            Id = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 431, DateTimeKind.Utc).AddTicks(991),
                            IsDeleted = false,
                            Name = "Category-3"
                        },
                        new
                        {
                            Id = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 431, DateTimeKind.Utc).AddTicks(996),
                            IsDeleted = false,
                            Name = "Category-4"
                        },
                        new
                        {
                            Id = new Guid("f1dc7eeb-85ed-9967-0e32-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 431, DateTimeKind.Utc).AddTicks(1001),
                            IsDeleted = false,
                            Name = "Category-5"
                        });
                });

            modelBuilder.Entity("ProductManagement.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ecb25ec-4248-4862-b7be-c0f8533d2ec4"),
                            Barcode = "123456789",
                            CategoryId = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(62),
                            Description = "Descrition-1",
                            IsDeleted = false,
                            Name = "Product-1",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("74197aa1-f129-4b00-ae4b-2bf4acafb564"),
                            Barcode = "123456789",
                            CategoryId = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(73),
                            Description = "Descrition-2",
                            IsDeleted = false,
                            Name = "Product-2",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("fa3d93c9-e2ca-463d-97c7-3153a0284716"),
                            Barcode = "123456789",
                            CategoryId = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(82),
                            Description = "Descrition-3",
                            IsDeleted = false,
                            Name = "Product-3",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("cb2bba1f-b325-4286-b926-3bd19487d5a2"),
                            Barcode = "123456789",
                            CategoryId = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(89),
                            Description = "Descrition-4",
                            IsDeleted = false,
                            Name = "Product-4",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("5231f2df-081e-46ed-9f8d-0051eb389be7"),
                            Barcode = "123456789",
                            CategoryId = new Guid("6866ae00-820d-ec66-9c60-3a0f48228716"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(96),
                            Description = "Descrition-5",
                            IsDeleted = false,
                            Name = "Product-5",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("46adea2c-ef9d-4a48-8a51-c950d0336ba5"),
                            Barcode = "123456789",
                            CategoryId = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(133),
                            Description = "Descrition-6",
                            IsDeleted = false,
                            Name = "Product-6",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("48250c6f-808c-4227-9256-f5da9e4ecc50"),
                            Barcode = "123456789",
                            CategoryId = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(140),
                            Description = "Descrition-7",
                            IsDeleted = false,
                            Name = "Product-7",
                            Status = (byte)1,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("065b7d83-eaa9-4df9-a630-c5c057386369"),
                            Barcode = "123456789",
                            CategoryId = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(148),
                            Description = "Descrition-8",
                            IsDeleted = false,
                            Name = "Product-8",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("e42e9580-80d8-41f3-a819-b61ffdaa0969"),
                            Barcode = "123456789",
                            CategoryId = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(156),
                            Description = "Descrition-9",
                            IsDeleted = false,
                            Name = "Product-9",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("a95cc2a3-547c-4585-9434-3325eb98a5eb"),
                            Barcode = "123456789",
                            CategoryId = new Guid("a8452e0c-40b2-df77-0408-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(163),
                            Description = "Descrition-10",
                            IsDeleted = false,
                            Name = "Product-10",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("2c2b97ae-01cd-4b95-afdc-fea237aa56a3"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(171),
                            Description = "Descrition-11",
                            IsDeleted = false,
                            Name = "Product-11",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("550e3e5e-b7dc-43fc-9866-268e3868a27e"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(178),
                            Description = "Descrition-12",
                            IsDeleted = false,
                            Name = "Product-12",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("c14e6f99-2ef0-483e-ab52-c11179f67214"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(185),
                            Description = "Descrition-13",
                            IsDeleted = false,
                            Name = "Product-13",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("57083701-90e0-45a0-9463-b8453e7ff336"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(201),
                            Description = "Descrition-14",
                            IsDeleted = false,
                            Name = "Product-14",
                            Status = (byte)2,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("8454bc32-1643-4641-b7b3-60bfa2c99048"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c72bf8dd-dab6-d187-048c-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(208),
                            Description = "Descrition-15",
                            IsDeleted = false,
                            Name = "Product-15",
                            Status = (byte)0,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("f68af4a3-a354-4404-934c-a67503890727"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(215),
                            Description = "Descrition-16",
                            IsDeleted = false,
                            Name = "Product-16",
                            Status = (byte)0,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("5d18146f-f6d1-41ad-9f34-88f04371d535"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(223),
                            Description = "Descrition-17",
                            IsDeleted = false,
                            Name = "Product-17",
                            Status = (byte)0,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("639d3da3-814e-426f-af77-b63056977142"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(231),
                            Description = "Descrition-18",
                            IsDeleted = false,
                            Name = "Product-18",
                            Status = (byte)0,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("c4899242-9e13-42fd-90b9-a64ec88d9307"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(238),
                            Description = "Descrition-19",
                            IsDeleted = false,
                            Name = "Product-19",
                            Status = (byte)0,
                            Weight = 10m
                        },
                        new
                        {
                            Id = new Guid("b3462ec3-1d6d-4af0-a109-e689f67f8708"),
                            Barcode = "123456789",
                            CategoryId = new Guid("c0b86591-0a77-be3a-0a64-3a0f48228717"),
                            CreationTime = new DateTime(2024, 3, 23, 0, 14, 29, 432, DateTimeKind.Utc).AddTicks(245),
                            Description = "Descrition-20",
                            IsDeleted = false,
                            Name = "Product-20",
                            Status = (byte)0,
                            Weight = 10m
                        });
                });

            modelBuilder.Entity("ProductManagement.Products.Product", b =>
                {
                    b.HasOne("ProductManagement.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagement.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
